
            

name: Link Jira Tickets

on:
  pull_request:
    types: [opened, edited]

jobs:
  link_tickets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Extract and link Jira tickets
      id: link_tickets
      run: |
        python3 link_tickets.py "${{ github.event.pull_request.body }}"
        echo "::set-output name=jira_tickets::$(cat link_tickets_output.txt)"
    
    - name: Get current PR description
      id: get_description
      run: |
        PR_NUMBER=${{ github.event.number }}
        DESCRIPTION=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} | jq -r '.body')
        echo "::set-output name=description::${DESCRIPTION}"
      shell: bash
    
    - name: Merge existing description with Jira tickets
      id: merge_description
      run: |
        JIRA_TICKETS="${{ steps.link_tickets.outputs.jira_tickets }}"
        DESCRIPTION="${{ steps.get_description.outputs.description }}"
        
        if [[ -z "${DESCRIPTION}" ]]; then
          echo "${JIRA_TICKETS}" > new_description.txt
        else
          echo "${DESCRIPTION}" > new_description.txt
          echo -e "\n\n${JIRA_TICKETS}" >> new_description.txt
        fi
        echo "::set-output name=new_description::$(cat new_description.txt)"
      shell: bash
    
    - name: Update PR description
      run: |
        PR_NUMBER=${{ github.event.number }}
        NEW_DESCRIPTION="${{ steps.merge_description.outputs.new_description }}"
        
        curl -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} \
          -d "{\"body\": \"${NEW_DESCRIPTION}\"}"
