
            

name: Link Jira Tickets

on:
  pull_request:
    types: [opened, edited]

jobs:
  link_tickets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Extract and link Jira tickets
      run: |
        python3 link_tickets.py "${{ github.event.pull_request.body }}"
      id: link_tickets
      
    - name: Update PR description
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Link Jira Tickets"
        title: "Link Jira Tickets"
        body: ${{ steps.link_tickets.outputs.jira_tickets }}
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
